### ISSUE TITLE
Extension still tries to authenticate with GitHub despite proxy settings

### ISSUE THREAD

**Issue by marclipovsky** [bernardo-bruning/ollama-copilot#1]
I've attempted to use this extension, I've installed ollama-codepilot, updated the settings to use the proxy, and have it running however it looks like Github Copilot [Chat] extensions still try and authenticate with Github.

<img width="324" alt="Screenshot 2024-05-10 at 12 25 10 AM" src="https://github.com/bernardo-bruning/ollama-copilot/assets/112484/76fdf972-1054-414d-865d-b59f2fcd4336">

Any idea what might be missing? Thanks!

**Comment by bernardo-bruning** [comment]
Hi @marclipovsky. I changed the instructions now because of your question. I recommend removing the proxy settings, signing up or logging into github and after then enabling the proxy setting in vscode.

https://github.com/bernardo-bruning/ollama-copilot/pull/2

Can you test and confirm ?

**Comment by marclipovsky** [comment]
I'm running this on macOS but I noticed an error when installed that said it was meant for Linux. Would that impact functionality?

**Comment by marclipovsky** [comment]
The above doesn't look like it should be an issue.

OK I logged in to my Github account and I can see copilot working with Github API. I've changed the debugging hostname to what's describe in the readme BUT I'm not gettng any traffic to http://localhost:11437. `ollama-copilot` does not output anything either.

**Comment by marclipovsky** [comment]
Ok I believe the model flag isn't work as expected. I wanted to use `codellama:latest` instead of `codellama:code`. When running `ollama-copilot --model=codellama:latest`, I get no requests made to localhost. I cloned the repo to run the program myself. I changed the default value for the model flag to `codellama:latest` and ran `go run main.go`. Everything worked fine then.

**Comment by marclipovsky** [comment]
Found the issue. `model` is never used. Creating a PR now.

**Comment by entropitor** [comment]
I'm getting a similar error on neovim, nothing wants to work without doing `:Copilot setup` which requires going to github.

**Comment by hrmJ** [comment]
Ah me too, wonder if there is any way to skip the Copilot setup step?
