### ISSUE TITLE
Dúvida 

### ISSUE THREAD

**Issue by guilhermecgs** [bernardo-bruning/ollama-copilot#4]
Bernardo,

Como esse projeto é diferente do continue.dev, que suporta o ollama?

Pelo o que eu entendi, aqui é um proxy? A motivação é segurança e privacidade ou outra coisa?

**Comment by bernardo-bruning** [comment]
Acredito que a diferença seja arquitetura de solução apenas. 

O proposito aqui é utilizar plugins de copilot existentes, sendo este o cliente da solução. Já o ollama-copilot acaba atuando como o servidor do github copilot, por isso se torna um proxy atendendo o contrato do github para o ollama. 

Isso possibilita um uso mais amplo de IDEs, como no meu caso neovim.
