### ISSUE TITLE
is there a limit to the copilot.vim version?

### ISSUE THREAD

**Issue by lasypig** [bernardo-bruning/ollama-copilot#6]
2024/05/14 18:02:26 failed to transfer: writeto tcp 127.0.0.1:51306->127.0.0.1:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:32824: use of closed network connection
2024/05/14 18:02:26 http: TLS handshake error from 127.0.0.1:51306: EOF
2024/05/14 18:02:26 failed to transfer: writeto tcp 127.0.0.1:51316->127.0.0.1:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:32828: use of closed network connection
2024/05/14 18:02:26 http: TLS handshake error from 127.0.0.1:51316: EOF
2024/05/14 18:02:26 failed to transfer: writeto tcp 127.0.0.1:51330->127.0.0.1:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:32840: use of closed network connection
2024/05/14 18:02:26 http: TLS handshake error from 127.0.0.1:51330: EOF
2024/05/14 18:02:26 http: TLS handshake error from 127.0.0.1:51346: EOF
2024/05/14 18:02:26 failed to transfer: writeto tcp 127.0.0.1:51346->127.0.0.1:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:32852: use of closed network connection
2024/05/14 18:02:27 failed to transfer: writeto tcp 127.0.0.1:51354->127.0.0.1:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:32858: use of closed network connection
2024/05/14 18:02:27 http: TLS handshake error from 127.0.0.1:51354: EOF
2024/05/14 18:02:27 http: TLS handshake error from 127.0.0.1:51356: EOF

**Comment by bernardo-bruning** [comment]
Which copilot.vim version are you using?

I think the copilot came in some moments the connection is closed unexpectedly producing these logs. But it continues to work in my environment.

I'm working to fix these logs.

**Comment by lasypig** [comment]
> Which copilot.vim version are you using?您使用的是哪个版本的 copilot.vim？
> 
> I think the copilot came in some moments the connection is closed unexpectedly producing these logs. But it continues to work in my environment.我认为是 copilot 在连接意外关闭的某些时刻产生了这些日志。但在我的环境中，它还能继续工作。
> 
> I'm working to fix these logs.我正在修复这些日志。

my copilot.vim version is 1.31.0.

**Comment by bernardo-bruning** [comment]
The last version provider num_predicts that enable return fast response. I think that is possible configure context timeout in future changes too
